### ISSUE TITLE
CachingAssetAccessor accidentally cache an invalidate response

### ISSUE THREAD

**Issue by baothientran** [CesiumGS/cesium-native#152]
Report at https://github.com/CesiumGS/cesium-unreal-demo/issues/17

The accessor usually checks the status code to be a success response before caching it. However, it seems to be the status code is not enough to determine if the response is valid.

**Comment by argallegos** [comment]
Just wanted to note that this is still an issue, albeit a very rare one. Even reinstalling the plugin and UE does not seem to fix this, and it can result in no tilesets loading. 

Seems to always come with the following error message:
`LogCesiumNative: Error: [2021-03-04 16:37:40.959] [error] [Tileset.cpp:464] Error when parsing tileset JSON, error code 3 at byte offset 0`

To fix:
While the UE editor is CLOSED, open Windows explorer to `%userprofile%\AppData\Local\UnrealEngine\4.26`. Delete the `cesium-request-cache.sqlite` file inside that directory.

**Comment by shehzan10** [comment]
> While the UE editor is CLOSED, open Windows explorer to `%userprofile%\AppData\Local\UnrealEngine\4.26`. Delete the `cesium-request-cache.sqlite` file inside that directory.

As a workaround this might be ok temporarily. Should the proper solution be to add a frontend button to clear cache?

**Comment by azrogers** [comment]
@kring Has this been fixed with the latest CachingAssetAccessor changes?

**Comment by kring** [comment]
Let's close this. To anyone that thinks they're still experiencing this problem, please re-open the issue and provide as much detail as you can.
